### ISSUE TITLE
module is not found in the `*.d.ts`

### ISSUE THREAD

**Issue by GinMu** [swtcca/swtclib#41]
version:
@swtc/serializer: 1.0.3
@swtc/wallet: 1.0.4

<img width="867" alt="Screen Shot 2020-02-15 at 14 32 59" src="https://user-images.githubusercontent.com/12183493/74583283-79171780-5000-11ea-8c16-1637a39b438f.png">

**Comment by lospringliu** [comment]
和 lerna 有关， 你试试最新的版本，应该解决了

**Comment by GinMu** [comment]
> 和 lerna 有关， 你试试最新的版本，应该解决了

ok
