### ISSUE TITLE
多重签名备注问题

### ISSUE THREAD

**Issue by zhaitianye** [swtcca/swtclib#49]
![image](https://user-images.githubusercontent.com/26245879/88530006-579c6c00-d033-11ea-9c2d-bd5977ce2d38.png)
多重签名备注好像是转换成hex转换了两次，具体在 transaction/ memo_normalize 这个方法里面，我这边测试的是转换了两次。具体还不能确定。麻烦有时间看一下。

**Comment by zhaitianye** [comment]
我在贴两种图描述下问题：
![微信截图_20200728111655](https://user-images.githubusercontent.com/26245879/88615502-a6461680-d0c4-11ea-8aa7-eadb8eb36f82.png)
第一张图，用的hex格式的 1 ，转换为hex是31，类型 hex转换了两次成了 363836353738 ，这个没有问题，可以正常交易，在区块链浏览器可以正常解析
![QQ图片20200728111916](https://user-images.githubusercontent.com/26245879/88615509-a8a87080-d0c4-11ea-8553-9fe77ba5428f.png)
第二张图，用的字符串格式的 测试 ，类型在记录上链的时候没有指定类型（这里猜想应该是默认是str格式的），转成hex也转换了两次。可以交易成功，但是浏览器不能正常解析，浏览器只进行反转换回来了一次。

**Comment by zhaitianye** [comment]
文档方面主要用到了 https://swtcdoc.netlify.app/docs/api/#buildMultisignTx 这里的 11.5.1 11.5.2 11.5.3 部分。
这一块，在年前的时候备注信息测试的是没有问题的，是不是最新的更新影响到这块。具体还需要在核查一下。

**Comment by zhaitianye** [comment]
![image](https://user-images.githubusercontent.com/26245879/88626096-9e926c00-d0dc-11ea-88ad-117117641fe9.png)
找了一下历史的提交，有可能是这次的提交影响的。看一下，是否可以定位到问题。

**Comment by lospringliu** [comment]
#### 最新memo支持
- 默认字符串格式
- 只有明确要求时才使用`hex`格式 `tx.addMemo("hexstring", "hex")` 。 长度为奇数时后面补零
- `json`格式 `tx.addMemo({key: "value"})`

目前单签和多签同时支持

**Comment by lospringliu** [comment]
```
{
    "account": "j95iYnY2yt7SfxVjQEzbJBusAYXSk1vK4n",
    "ledger_index_max": 16647048,
    "ledger_index_min": 266955,
    "limit": 1,
    "marker": {
        "ledger": 16646779,
        "seq": 0
    },
    "transactions": [
        {
            "amount": {
                "currency": "SWT",
                "issuer": "",
                "value": "0.01"
            },
            "balances": {
                "SWT": 40.79
            },
            "balancesPrev": {
                "SWT": 40.82
            },
            "counterparty": "jfqiMxoT228vp3dMrXKnJXo6V9iYEx94pt",
            "date": 1596316750,
            "effects": [],
            "fee": "0.02",
            "hash": "6936AD8E95C29E0CC28A31E1D63543F50A3FA187538E7F271937059935F66BF8",
            "ledger_index": 16647046,
            "memos": [
                {
                    "MemoData": "中国"
                },
                {
                    "MemoData": "abc123"
                },
                {
                    "MemoData": "ABCDEF0123456789A0",
                    "MemoFormat": "hex"
                },
                {
                    "MemoData": "{\"key\":\"value\"}",
                    "MemoFormat": "json"
                }
            ],
            "result": "tesSUCCESS",
            "signers": [
                "jpmKEm2sUevfpFjS7QHdT8Sx7ZGoEXTJAz",
                "jfqiMxoT228vp3dMrXKnJXo6V9iYEx94pt"
            ],
            "type": "sent"
        }
    ]
}
```
